/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInterface: typeof import('./components/ChatInterface.vue')['default']
    CompanionDrawer: typeof import('./components/CompanionDrawer.vue')['default']
    CompanionEdit: typeof import('./components/CompanionEdit.vue')['default']
    CompanionPreview: typeof import('./components/CompanionPreview.vue')['default']
    CreateNewWife: typeof import('./components/CreateNewWife.vue')['default']
    FloatingChatInterface: typeof import('./components/FloatingChatInterface.vue')['default']
    Live2dComponent: typeof import('./components/Live2dComponent.vue')['default']
    PreviousChatInterface: typeof import('./components/PreviousChatInterface.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechBubble: typeof import('./components/SpeechBubble.vue')['default']
    UserSetting: typeof import('./components/UserSetting.vue')['default']
  }
}
