/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatComponent: typeof import('./components/ChatComponent.vue')['default']
    ChatInterface: typeof import('./components/ChatInterface.vue')['default']
    CompanionDrawer: typeof import('./components/CompanionDrawer.vue')['default']
    CreateNewWife: typeof import('./components/CreateNewWife.vue')['default']
    Live2dComponent: typeof import('./components/Live2dComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
