/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInterface: typeof import('./components/ChatInterface.vue')['default']
    CompanionDrawer: typeof import('./components/CompanionDrawer.vue')['default']
    CompanionEdit: typeof import('./components/CompanionEdit.vue')['default']
    CompanionPreview: typeof import('./components/CompanionPreview.vue')['default']
    HistoryDialogInterface: typeof import('./components/HistoryDialogInterface.vue')['default']
    Live2dComponent: typeof import('./components/Live2dComponent.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    LogoText: typeof import('./components/LogoText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechBubble: typeof import('./components/SpeechBubble.vue')['default']
    UserSettingListItem: typeof import('./components/UserSettingListItem.vue')['default']
  }
}
