/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CreateNewWaifu': RouteRecordInfo<'/CreateNewWaifu', '/CreateNewWaifu', Record<never, never>, Record<never, never>>,
    '/EditCurrentCompanion': RouteRecordInfo<'/EditCurrentCompanion', '/EditCurrentCompanion', Record<never, never>, Record<never, never>>,
    '/ErrorPage': RouteRecordInfo<'/ErrorPage', '/ErrorPage', Record<never, never>, Record<never, never>>,
    '/FacetimePage': RouteRecordInfo<'/FacetimePage', '/FacetimePage', Record<never, never>, Record<never, never>>,
    '/LiveChatPage': RouteRecordInfo<'/LiveChatPage', '/LiveChatPage', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Main': RouteRecordInfo<'/Main', '/Main', Record<never, never>, Record<never, never>>,
    '/SignUp': RouteRecordInfo<'/SignUp', '/SignUp', Record<never, never>, Record<never, never>>,
    '/TestPage': RouteRecordInfo<'/TestPage', '/TestPage', Record<never, never>, Record<never, never>>,
  }
}
